import { useCallback, useEffect, useState } from 'react'
import { OperationsNavigation, type OperationsSection } from '../components/OperationsNavigation'
import { ConfirmDialog } from '../components/ConfirmDialog'
import { EmptyState } from '../components/EmptyState'
import { StatusBadge } from '../components/StatusBadge'
import type { OperationsSnapshot } from '../../../../shared/operations/contracts'
import { BudgetPage } from './BudgetPage'
import { ConflictTablePage } from './ConflictTablePage'

export function OperationsPageSafe() {
  const [section, setSection] = useState<OperationsSection>('quote'); const [snapshot, setSnapshot] = useState<OperationsSnapshot>(); const [notice, setNotice] = useState(''); const [confirm, setConfirm] = useState(false); const [pendingBackup, setPendingBackup] = useState<string>()
  const reload = useCallback(() => window.coreDesk?.operations.getSnapshot().then(setSnapshot), [])
  useEffect(() => { void reload() }, [reload])
  const importData = async () => { setConfirm(false); await window.coreDesk?.operations.confirmImport(); await reload(); setNotice('Importação concluída.') }
  const restore = async () => { if (!pendingBackup) return; setConfirm(false); await window.coreDesk?.operations.restoreBackup(pendingBackup); setPendingBackup(undefined); await reload(); setNotice('Backup restaurado.') }
  const content = section === 'quote' ? <BudgetPage snapshot={snapshot} onSaved={() => { void reload(); setNotice('Orçamento salvo no histórico.') }} onNotice={setNotice} /> : section === 'tables' ? <ConflictTablePage onSectionChange={setSection} /> : section === 'companies' ? <CompaniesPanel /> : section === 'history' ? <HistoryPanel snapshot={snapshot} /> : section === 'import' ? <ImportPanel onConfirm={() => setConfirm(true)} /> : section === 'backups' ? <BackupPanel onRestore={(name) => { setPendingBackup(name); setConfirm(true) }} /> : section === 'audit' ? <AuditPanel /> : <EntityPanel section={section} snapshot={snapshot} onReload={reload} />
  return <main className="flex min-h-0 min-w-0 flex-1 flex-col bg-core-canvas text-sm text-slate-200"><OperationsNavigation active={section} onChange={setSection} /><section className="min-w-0 flex-1 overflow-auto p-4"><header className="mb-4 flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-core-accent">Workspace operacional</p><h1 className="text-xl font-semibold text-white">{section === 'quote' ? 'Orçamento' : section[0].toUpperCase() + section.slice(1)}</h1><p className="mt-1 text-xs text-slate-500">Operações compactas e rastreáveis.</p></div>{notice && <span className="text-xs text-core-accent">{notice}</span>}</header>{content}</section><ConfirmDialog open={confirm} title={pendingBackup ? 'Restaurar backup' : 'Confirmar importação'} message={pendingBackup ? 'A restauração substitui os dados operacionais atuais.' : 'Os arquivos originais não serão alterados.'} confirmLabel={pendingBackup ? 'RESTAURAR' : 'Importar'} onCancel={() => { setConfirm(false); setPendingBackup(undefined) }} onConfirm={() => void (pendingBackup ? restore() : importData())} /></main>
}

function CompaniesPanel() { const [items, setItems] = useState<Awaited<ReturnType<NonNullable<Window['coreDesk']>['operations']['listOperationalCompanies']>>>([]); const [status, setStatus] = useState<'active' | 'archived'>('active'); const [query, setQuery] = useState(''); const [name, setName] = useState(''); const [code, setCode] = useState(''); const load = useCallback(() => window.coreDesk!.operations.listOperationalCompanies(status).then(setItems), [status]); useEffect(() => { void load() }, [load]); const save = async () => { if (!name.trim() || !code.trim()) return; await window.coreDesk!.operations.saveOperationalCompany({ name, code }); setName(''); setCode(''); await load() }; const filtered = items.filter((item) => `${item.name} ${item.code}`.toLowerCase().includes(query.toLowerCase())); return <div className="rounded-lg border border-core-line bg-core-panel p-3"><div className="mb-3 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Pesquisar empresas" aria-label="Pesquisar empresas" className="min-w-0 flex-1 rounded border border-core-line bg-core-canvas px-2 py-2 text-xs text-white" /><select value={status} onChange={(event) => setStatus(event.target.value as 'active' | 'archived')} aria-label="Status das empresas" className="rounded border border-core-line bg-core-canvas px-2 py-2 text-xs text-white"><option value="active">Ativas</option><option value="archived">Arquivadas</option></select></div><div className="mb-4 grid gap-2 md:grid-cols-3"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Nome" aria-label="Nome da empresa" className="rounded border border-core-line bg-core-canvas px-2 py-2 text-xs text-white" /><input value={code} onChange={(event) => setCode(event.target.value)} placeholder="Código" aria-label="Código da empresa" className="rounded border border-core-line bg-core-canvas px-2 py-2 text-xs text-white" /><button onClick={() => void save()} className="rounded bg-core-accent px-3 py-2 text-xs font-semibold text-slate-950">Adicionar empresa</button></div>{filtered.map((item) => <div key={item.id} className="flex justify-between border-b border-core-line/60 px-2 py-2 text-xs"><span>{item.name} <span className="text-slate-500">{item.code}</span></span><StatusBadge status={item.status} /></div>)}{!filtered.length && <EmptyState text="Nenhuma empresa encontrada." />}</div> }
function EntityPanel({ section, snapshot, onReload }: { section: 'bases' | 'insurers' | 'specialties'; snapshot?: OperationsSnapshot; onReload: () => void }) { const items = section === 'bases' ? snapshot?.bases ?? [] : section === 'insurers' ? snapshot?.insurers ?? [] : snapshot?.specialties ?? []; return <div className="rounded-lg border border-core-line bg-core-panel p-3"><div className="mb-3 flex items-center justify-between"><span className="text-xs text-slate-400">{items.length} registros</span><button onClick={onReload} aria-label="Atualizar registros" className="rounded border border-core-line px-2 py-1 text-xs">Atualizar</button></div>{items.map((item) => <div key={item.id} className="border-b border-core-line/60 px-2 py-2 text-xs">{item.name}</div>)}{!items.length && <EmptyState text="Nenhum registro encontrado." />}</div> }
function HistoryPanel({ snapshot }: { snapshot?: OperationsSnapshot }) { const items = snapshot?.quotes ?? []; return <div className="rounded-lg border border-core-line bg-core-panel p-3">{items.map((item) => <div key={item.id} className="flex justify-between border-b border-core-line/60 px-2 py-2 text-xs"><span>{item.origin} → {item.destination}</span><StatusBadge status={item.status} /></div>)}{!items.length && <EmptyState text="Nenhum orçamento salvo." />}</div> }
function ImportPanel({ onConfirm }: { onConfirm: () => void }) { return <div className="rounded-lg border border-core-line bg-core-panel p-4"><p className="mb-3 text-xs text-slate-400">Importação somente leitura até a confirmação.</p><button onClick={onConfirm} className="rounded bg-core-accent px-3 py-2 text-xs font-semibold text-slate-950">Confirmar importação</button></div> }
function BackupPanel({ onRestore }: { onRestore: (name: string) => void }) { const [items, setItems] = useState<string[]>([]); useEffect(() => { void window.coreDesk?.operations.listBackups().then(setItems) }, []); return <div className="rounded-lg border border-core-line bg-core-panel p-3">{items.map((name) => <div key={name} className="flex justify-between border-b border-core-line/60 px-2 py-2 text-xs"><span>{name}</span><button onClick={() => onRestore(name)} className="rounded border border-core-line px-2 py-1">Restaurar</button></div>)}{!items.length && <EmptyState text="Ainda não existem backups operacionais." />}</div> }
function AuditPanel() { const [items, setItems] = useState<Array<{ id: string; timestamp: string; action: string; entity: string; summary: string }>>([]); useEffect(() => { void window.coreDesk?.operations.listAudit().then(setItems) }, []); return <div className="rounded-lg border border-core-line bg-core-panel p-3">{items.map((item) => <div key={item.id} className="border-b border-core-line/60 px-2 py-2 text-xs">{new Date(item.timestamp).toLocaleString('pt-BR')} · {item.action} · {item.entity} · {item.summary}</div>)}{!items.length && <EmptyState text="Ainda não existem alterações auditadas." />}</div> }
