import { describe, expect, it } from 'vitest'
import { applyLegacyPriceTableCompanyMigration, detectActivePriceTableConflicts, normalizeLegacyCompanyName, previewLegacyPriceTableCompanyMigration, resolveOperationalCompanyForLegacyTable, resolvePriceTableConflict } from '../shared/operations/migration'
const companies = [{ id: 'c1', name: 'Resgate 116', normalizedName: 'resgate 116', code: 'RESGATE_116', status: 'active' as const, createdAt: '', updatedAt: '' }, { id: 'c2', name: 'Auto Elite', normalizedName: 'auto elite', code: 'AUTO_ELITE', status: 'active' as const, createdAt: '', updatedAt: '' }, { id: 'c3', name: 'Help Go', normalizedName: 'help go', code: 'HELP_GO', status: 'active' as const, createdAt: '', updatedAt: '' }]
const table = { id: 't1', company: ' RESGATE-116 ', insurerId: 'i1', specialtyId: 's1', exitValue: 10, kmFranchise: 40, kmValue: 2, status: 'active' as const }
describe('legacy pricing company migration', () => {
  it('normalizes deterministic names', () => expect(normalizeLegacyCompanyName(' RESGATE  116 ')).toBe('resgate 116'))
  it('resolves and preserves legacy identity', () => { expect(resolveOperationalCompanyForLegacyTable({ legacyCompanyName: 'auto-elite', operationalCompanies: companies }).status).toBe('resolved'); const result = applyLegacyPriceTableCompanyMigration({ priceTables: [table], operationalCompanies: companies }); expect((result.tables[0] as typeof table & { companyId?: string }).companyId).toBe('c1'); expect((result.tables[0] as typeof table & { legacyCompanyName?: string }).legacyCompanyName).toBe(' RESGATE-116 ') })
  it('preview does not mutate and unknown stays pending', () => { const unknown = { ...table, id: 't2', company: 'Unknown' }; const result = previewLegacyPriceTableCompanyMigration({ priceTables: [unknown], operationalCompanies: companies }); expect(result.needsReview).toBe(1); expect((unknown as typeof unknown & { companyId?: string }).companyId).toBeUndefined() })
  it('marks and resolves duplicate active combinations without deleting records', () => { const result = applyLegacyPriceTableCompanyMigration({ priceTables: [table, { ...table, id: 't2' }], operationalCompanies: companies }); const groups = detectActivePriceTableConflicts(result.tables); expect(groups).toHaveLength(1); const resolved = resolvePriceTableConflict(result.tables, groups[0], 't1'); expect(resolved).toHaveLength(2); expect(resolved.find((item) => item.id === 't2')?.status).toBe('archived'); expect(detectActivePriceTableConflicts(resolved)).toHaveLength(0) })
})
