import type { OperationalCompany, PricingTable } from './models'

export type LegacyCompanyResolution = { status: 'resolved'; companyId: string; companyName: string; normalizedLegacyName: string } | { status: 'not-found'; legacyCompanyName: string; normalizedLegacyName: string } | { status: 'ambiguous'; legacyCompanyName: string; candidateCompanyIds: string[] }
export type MigrationMapping = { priceTableId: string; legacyCompanyName?: string; companyId?: string; companyName?: string; status: string; reason?: string }
export interface LegacyCompanyMigrationReport { startedAt: string; completedAt: string; totalTables: number; alreadyNative: number; autoMapped: number; needsReview: number; ambiguous: number; failed: number; mappings: MigrationMapping[] }
type MigratableTable = PricingTable & { companyId?: string; legacyCompanyName?: string; specialtyName?: string; migrationStatus?: 'native' | 'auto-mapped' | 'needs-review'; migrationReason?: string }
export interface PriceTableConflictGroup { id: string; companyId: string; insurerId: string; specialtyKey: string; priceTableIds: string[]; count: number }
export function normalizeLegacyCompanyName(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[._-]+/g, ' ').replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ').trim() }
export function resolveOperationalCompanyForLegacyTable(input: { legacyCompanyName?: string; operationalCompanies: OperationalCompany[] }): LegacyCompanyResolution { const legacy = input.legacyCompanyName ?? ''; const normalizedLegacyName = normalizeLegacyCompanyName(legacy); const candidates = input.operationalCompanies.filter((company) => normalizeLegacyCompanyName(company.name) === normalizedLegacyName); if (candidates.length === 1) return { status: 'resolved', companyId: candidates[0].id, companyName: candidates[0].name, normalizedLegacyName }; if (candidates.length > 1) return { status: 'ambiguous', legacyCompanyName: legacy, candidateCompanyIds: candidates.map((item) => item.id) }; return { status: 'not-found', legacyCompanyName: legacy, normalizedLegacyName } }
export function previewLegacyPriceTableCompanyMigration(input: { priceTables: PricingTable[]; operationalCompanies: OperationalCompany[] }) { const startedAt = new Date().toISOString(); const mappings: MigrationMapping[] = []; let alreadyNative = 0; let autoMapped = 0; let needsReview = 0; let ambiguous = 0; for (const raw of input.priceTables) { const table = raw as MigratableTable; if (table.companyId && table.migrationStatus !== 'needs-review') { alreadyNative++; mappings.push({ priceTableId: table.id, companyId: table.companyId, status: 'already-native' }); continue } const resolution = resolveOperationalCompanyForLegacyTable({ legacyCompanyName: table.legacyCompanyName ?? table.company, operationalCompanies: input.operationalCompanies }); if (resolution.status === 'resolved') { autoMapped++; mappings.push({ priceTableId: table.id, legacyCompanyName: table.legacyCompanyName ?? table.company, companyId: resolution.companyId, companyName: resolution.companyName, status: 'auto-mapped' }) } else if (resolution.status === 'ambiguous') { ambiguous++; mappings.push({ priceTableId: table.id, legacyCompanyName: resolution.legacyCompanyName, status: 'ambiguous', reason: 'Mais de uma empresa corresponde ao nome normalizado.' }) } else { needsReview++; mappings.push({ priceTableId: table.id, legacyCompanyName: resolution.legacyCompanyName, status: 'needs-review', reason: 'Empresa legada não encontrada.' }) } } return { startedAt, completedAt: new Date().toISOString(), totalTables: input.priceTables.length, alreadyNative, autoMapped, needsReview, ambiguous, failed: 0, mappings } satisfies LegacyCompanyMigrationReport }
export function applyLegacyPriceTableCompanyMigration(input: { priceTables: PricingTable[]; operationalCompanies: OperationalCompany[]; now?: string }) { const report = previewLegacyPriceTableCompanyMigration(input); const byId = new Map(report.mappings.map((item) => [item.priceTableId, item])); const mapped = input.priceTables.map((raw) => { const table = { ...(raw as MigratableTable) }; const mapping = byId.get(table.id); if (!mapping || mapping.status !== 'auto-mapped') return table; table.legacyCompanyName = table.legacyCompanyName ?? table.company; table.companyId = mapping.companyId; table.migrationStatus = 'auto-mapped'; table.migrationReason = 'Correspondência normalizada inequívoca.'; return table }); const tables = markPriceTableConflicts(mapped); return { report: { ...report, conflicts: detectActivePriceTableConflicts(tables).length, conflictingRecords: detectActivePriceTableConflicts(tables).reduce((sum, group) => sum + group.count, 0) }, tables } }
export function detectActivePriceTableConflicts(priceTables: PricingTable[]): PriceTableConflictGroup[] { const groups = new Map<string, string[]>(); for (const raw of priceTables) { const table = raw as MigratableTable & { conflictStatus?: string }; if (table.status !== 'active' || !table.companyId || table.migrationStatus === 'needs-review') continue; const key = `${table.companyId}|${table.insurerId}|${table.specialtyId || normalizeLegacyCompanyName(table.specialtyName ?? '')}`; groups.set(key, [...(groups.get(key) ?? []), table.id]) } return [...groups.entries()].filter(([, ids]) => ids.length > 1).map(([key, ids]) => { const [companyId, insurerId, specialtyKey] = key.split('|'); return { id: `conflict:${key}`, companyId, insurerId, specialtyKey, priceTableIds: ids, count: ids.length } }) }
export function markPriceTableConflicts(priceTables: PricingTable[]) { const conflicts = detectActivePriceTableConflicts(priceTables); const byId = new Map(conflicts.flatMap((group) => group.priceTableIds.map((id) => [id, group.id] as const))); return priceTables.map((raw) => { const table = { ...(raw as MigratableTable & { conflictStatus?: string; conflictGroupId?: string }) }; const group = byId.get(table.id); table.conflictStatus = group ? 'duplicate-active-combination' : 'none'; if (group) table.conflictGroupId = group; else delete table.conflictGroupId; return table }) }
export function resolvePriceTableConflict(priceTables: PricingTable[], conflict: PriceTableConflictGroup, keepId: string) { if (!conflict.priceTableIds.includes(keepId)) throw new Error('Tabela escolhida não pertence ao conflito.'); return priceTables.map((raw) => { const table = { ...(raw as MigratableTable & { conflictStatus?: string; conflictGroupId?: string; archivedAt?: string }) }; if (!conflict.priceTableIds.includes(table.id)) return table; if (table.id === keepId) { table.conflictStatus = 'none'; delete table.conflictGroupId; return table } table.status = 'archived'; table.conflictStatus = 'none'; delete table.conflictGroupId; table.archivedAt = new Date().toISOString(); return table }) }
